services:
  - type: web
    name: programme-sous-admin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn programme_sous_admin.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: programme_sous_admin.settings
      - key: PYTHON_VERSION
        value: 3.10
